# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LSMM_Rcpp <- function(Pvalue, Z, A, alpha = 0.1, pi1_ = 0.1, maxiter = 1e4L, tol = 1e-6) {
    .Call('_LSMM_LSMM_Rcpp', PACKAGE = 'LSMM', Pvalue, Z, A, alpha, pi1_, maxiter, tol)
}

LFM_Rcpp <- function(Pvalue, Z, alpha = 0.1, pi1_ = 0.1, maxiter = 1e4L, tol = 1e-6) {
    .Call('_LSMM_LFM_Rcpp', PACKAGE = 'LSMM', Pvalue, Z, alpha, pi1_, maxiter, tol)
}

TwoGroup_Rcpp <- function(Pvalue, alpha = 0.1, pi1_ = 0.1, maxiter = 1e4L, tol = 1e-6) {
    .Call('_LSMM_TwoGroup_Rcpp', PACKAGE = 'LSMM', Pvalue, alpha, pi1_, maxiter, tol)
}

